/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* CSS custom properties mapped exact matches */
        "outline-variant": "hsl(var(--outline-variant))",
        "error": "hsl(var(--error))",
        "on-error": "hsl(var(--on-error))",
        "tertiary-fixed": "hsl(var(--tertiary-fixed))",
        "surface-tint": "hsl(var(--surface-tint))",
        "on-background": "hsl(var(--on-background))",
        "primary-fixed": "hsl(var(--primary-fixed))",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        "tertiary-fixed-dim": "hsl(var(--tertiary-fixed-dim))",
        "on-primary-container": "hsl(var(--on-primary-container))",
        "on-surface": "hsl(var(--on-surface))",
        "tertiary": "hsl(var(--tertiary))",
        "error-container": "hsl(var(--error-container))",
        "inverse-primary": "hsl(var(--inverse-primary))",
        "on-secondary-fixed-variant": "hsl(var(--on-secondary-fixed-variant))",
        "outline": "hsl(var(--outline))",
        "secondary-container": "hsl(var(--secondary-container))",
        "on-primary-fixed": "hsl(var(--on-primary-fixed))",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "secondary-fixed-dim": "hsl(var(--secondary-fixed-dim))",
        "secondary": "hsl(var(--secondary))",
        "on-tertiary-fixed": "hsl(var(--on-tertiary-fixed))",
        "background": "hsl(var(--background))",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        "primary-container": "hsl(var(--primary-container))",
        "inverse-on-surface": "hsl(var(--inverse-on-surface))",
        "on-secondary-fixed": "hsl(var(--on-secondary-fixed))",
        "on-tertiary-container": "hsl(var(--on-tertiary-container))",
        "surface-bright": "hsl(var(--surface-bright))",
        "surface-dim": "hsl(var(--surface-dim))",
        "surface-container": "hsl(var(--surface-container))",
        "secondary-fixed": "hsl(var(--secondary-fixed))",
        "surface-variant": "hsl(var(--surface-variant))",
        "tertiary-container": "hsl(var(--tertiary-container))",
        "on-tertiary-fixed-variant": "hsl(var(--on-tertiary-fixed-variant))",
        "on-primary": "hsl(var(--on-primary))",
        "on-tertiary": "hsl(var(--on-tertiary))",
        "on-secondary": "hsl(var(--on-secondary))",
        "primary-fixed-dim": "hsl(var(--primary-fixed-dim))",
        "on-primary-fixed-variant": "hsl(var(--on-primary-fixed-variant))",
        "primary": "hsl(var(--primary))",
        "inverse-surface": "hsl(var(--inverse-surface))",
        "surface": "hsl(var(--surface))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "on-error-container": "hsl(var(--on-error-container))",
        "on-secondary-container": "hsl(var(--on-secondary-container))"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "80px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "48px",
        "base": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Poppins", "sans-serif"],
        "label-sm": ["Lato", "sans-serif"],
        "body-md": ["Lato", "sans-serif"],
        "body-lg": ["Lato", "sans-serif"],
        "label-md": ["Lato", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "headline-xl": ["Poppins", "sans-serif"],
        "headline-md": ["Poppins", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
